Mathoid 0 7 0
wikimedia/MathJax-node pull request #25
Opened 2017-11-01 11:13 UTC by physikerwelt

2017-11-01 11:14 UTC, physikerwelt commented on package.json
> +    "mathoid-mathjax": "git+https://github.com/physikerwelt/mathjax.git#up271"
This needs to be updated before we merge

2017-11-09 12:01 UTC, d00rman commented on .travis.yml
> +  - stable
Would be good to add Node 8 explicitly as well

2017-11-10 13:24 UTC, d00rman requested changes
There are conflicts in this PR, so they need to be resolved before we can merge/publish. Also see comment in package.json

2017-11-10 13:24 UTC, d00rman commented on package.json
> +    "mathoid-mathjax": "git+https://github.com/physikerwelt/mathjax.git#up271"
[MathJax@v2.7.1](https://github.com/wikimedia/MathJax/tree/v2.7.1) has been published, so this needs to be changed now to `"^2.7.1"`

2017-11-10 14:24 UTC, physikerwelt commented on package.json
> +    "mathoid-mathjax": "git+https://github.com/physikerwelt/mathjax.git#up271"
done

2017-11-10 14:24 UTC, physikerwelt commented on .travis.yml
> +  - stable
done

2017-11-13 09:13 UTC, d00rman approved these changes

2017-11-13 09:16 UTC, merged

2017-11-13 09:18 UTC, d00rman commented
Published as [v0.7.0](https://github.com/wikimedia/MathJax-node/tree/v0.7.0)